// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$44 {

    static final FunctionDescriptor _snwprintf_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _snwprintf_s_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_snwprintf_s_l",
        constants$44._snwprintf_s_l$FUNC
    );
    static final FunctionDescriptor _snwprintf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _snwprintf_s$MH = RuntimeHelper.downcallHandleVariadic(
        "_snwprintf_s",
        constants$44._snwprintf_s$FUNC
    );
    static final FunctionDescriptor _scwprintf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _scwprintf_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_scwprintf_l",
        constants$44._scwprintf_l$FUNC
    );
    static final FunctionDescriptor _scwprintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _scwprintf$MH = RuntimeHelper.downcallHandleVariadic(
        "_scwprintf",
        constants$44._scwprintf$FUNC
    );
    static final FunctionDescriptor _scwprintf_p_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _scwprintf_p_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_scwprintf_p_l",
        constants$44._scwprintf_p_l$FUNC
    );
    static final FunctionDescriptor _scwprintf_p$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _scwprintf_p$MH = RuntimeHelper.downcallHandleVariadic(
        "_scwprintf_p",
        constants$44._scwprintf_p$FUNC
    );
}


