// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$114 {

    static final FunctionDescriptor __p___argv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle __p___argv$MH = RuntimeHelper.downcallHandle(
        "__p___argv",
        constants$114.__p___argv$FUNC
    );
    static final FunctionDescriptor __p___wargv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle __p___wargv$MH = RuntimeHelper.downcallHandle(
        "__p___wargv",
        constants$114.__p___wargv$FUNC
    );
    static final FunctionDescriptor __p__environ$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle __p__environ$MH = RuntimeHelper.downcallHandle(
        "__p__environ",
        constants$114.__p__environ$FUNC
    );
    static final FunctionDescriptor __p__wenviron$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle __p__wenviron$MH = RuntimeHelper.downcallHandle(
        "__p__wenviron",
        constants$114.__p__wenviron$FUNC
    );
    static final FunctionDescriptor getenv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle getenv$MH = RuntimeHelper.downcallHandle(
        "getenv",
        constants$114.getenv$FUNC
    );
    static final FunctionDescriptor _dupenv_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _dupenv_s$MH = RuntimeHelper.downcallHandle(
        "_dupenv_s",
        constants$114._dupenv_s$FUNC
    );
}


