// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$59 {

    static final FunctionDescriptor _ftelli64_nolock$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _ftelli64_nolock$MH = RuntimeHelper.downcallHandle(
        "_ftelli64_nolock",
        constants$59._ftelli64_nolock$FUNC
    );
    static final FunctionDescriptor _fwrite_nolock$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _fwrite_nolock$MH = RuntimeHelper.downcallHandle(
        "_fwrite_nolock",
        constants$59._fwrite_nolock$FUNC
    );
    static final FunctionDescriptor _getc_nolock$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _getc_nolock$MH = RuntimeHelper.downcallHandle(
        "_getc_nolock",
        constants$59._getc_nolock$FUNC
    );
    static final FunctionDescriptor _putc_nolock$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _putc_nolock$MH = RuntimeHelper.downcallHandle(
        "_putc_nolock",
        constants$59._putc_nolock$FUNC
    );
    static final FunctionDescriptor _ungetc_nolock$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _ungetc_nolock$MH = RuntimeHelper.downcallHandle(
        "_ungetc_nolock",
        constants$59._ungetc_nolock$FUNC
    );
    static final FunctionDescriptor __p__commode$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle __p__commode$MH = RuntimeHelper.downcallHandle(
        "__p__commode",
        constants$59.__p__commode$FUNC
    );
}


