// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$43 {

    static final FunctionDescriptor swprintf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle swprintf_s$MH = RuntimeHelper.downcallHandleVariadic(
        "swprintf_s",
        constants$43.swprintf_s$FUNC
    );
    static final FunctionDescriptor _swprintf_p_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _swprintf_p_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_swprintf_p_l",
        constants$43._swprintf_p_l$FUNC
    );
    static final FunctionDescriptor _swprintf_p$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _swprintf_p$MH = RuntimeHelper.downcallHandleVariadic(
        "_swprintf_p",
        constants$43._swprintf_p$FUNC
    );
    static final FunctionDescriptor _swprintf_c_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _swprintf_c_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_swprintf_c_l",
        constants$43._swprintf_c_l$FUNC
    );
    static final FunctionDescriptor _swprintf_c$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _swprintf_c$MH = RuntimeHelper.downcallHandleVariadic(
        "_swprintf_c",
        constants$43._swprintf_c$FUNC
    );
    static final FunctionDescriptor _snwprintf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _snwprintf_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_snwprintf_l",
        constants$43._snwprintf_l$FUNC
    );
}


