// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$110 {

    static final FunctionDescriptor _mbstrlen_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mbstrlen_l$MH = RuntimeHelper.downcallHandle(
        "_mbstrlen_l",
        constants$110._mbstrlen_l$FUNC
    );
    static final FunctionDescriptor _mbstrnlen$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _mbstrnlen$MH = RuntimeHelper.downcallHandle(
        "_mbstrnlen",
        constants$110._mbstrnlen$FUNC
    );
    static final FunctionDescriptor _mbstrnlen_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mbstrnlen_l$MH = RuntimeHelper.downcallHandle(
        "_mbstrnlen_l",
        constants$110._mbstrnlen_l$FUNC
    );
    static final FunctionDescriptor mbtowc$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle mbtowc$MH = RuntimeHelper.downcallHandle(
        "mbtowc",
        constants$110.mbtowc$FUNC
    );
    static final FunctionDescriptor _mbtowc_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mbtowc_l$MH = RuntimeHelper.downcallHandle(
        "_mbtowc_l",
        constants$110._mbtowc_l$FUNC
    );
    static final FunctionDescriptor mbstowcs_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle mbstowcs_s$MH = RuntimeHelper.downcallHandle(
        "mbstowcs_s",
        constants$110.mbstowcs_s$FUNC
    );
}


