// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$36 {

    static final FunctionDescriptor _vfwscanf_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vfwscanf_s_l$MH = RuntimeHelper.downcallHandle(
        "_vfwscanf_s_l",
        constants$36._vfwscanf_s_l$FUNC
    );
    static final FunctionDescriptor vfwscanf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vfwscanf_s$MH = RuntimeHelper.downcallHandle(
        "vfwscanf_s",
        constants$36.vfwscanf_s$FUNC
    );
    static final FunctionDescriptor _vwscanf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vwscanf_l$MH = RuntimeHelper.downcallHandle(
        "_vwscanf_l",
        constants$36._vwscanf_l$FUNC
    );
    static final FunctionDescriptor vwscanf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vwscanf$MH = RuntimeHelper.downcallHandle(
        "vwscanf",
        constants$36.vwscanf$FUNC
    );
    static final FunctionDescriptor _vwscanf_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vwscanf_s_l$MH = RuntimeHelper.downcallHandle(
        "_vwscanf_s_l",
        constants$36._vwscanf_s_l$FUNC
    );
    static final FunctionDescriptor vwscanf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vwscanf_s$MH = RuntimeHelper.downcallHandle(
        "vwscanf_s",
        constants$36.vwscanf_s$FUNC
    );
}


