// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$73 {

    static final FunctionDescriptor _snprintf_c$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _snprintf_c$MH = RuntimeHelper.downcallHandleVariadic(
        "_snprintf_c",
        constants$73._snprintf_c$FUNC
    );
    static final FunctionDescriptor _snprintf_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _snprintf_s_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_snprintf_s_l",
        constants$73._snprintf_s_l$FUNC
    );
    static final FunctionDescriptor _snprintf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _snprintf_s$MH = RuntimeHelper.downcallHandleVariadic(
        "_snprintf_s",
        constants$73._snprintf_s$FUNC
    );
    static final FunctionDescriptor _scprintf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _scprintf_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_scprintf_l",
        constants$73._scprintf_l$FUNC
    );
    static final FunctionDescriptor _scprintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _scprintf$MH = RuntimeHelper.downcallHandleVariadic(
        "_scprintf",
        constants$73._scprintf$FUNC
    );
    static final FunctionDescriptor _scprintf_p_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _scprintf_p_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_scprintf_p_l",
        constants$73._scprintf_p_l$FUNC
    );
}


