// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$149 {

    static final FunctionDescriptor ffmcrd$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffmcrd$MH = RuntimeHelper.downcallHandle(
        "ffmcrd",
        constants$149.ffmcrd$FUNC
    );
    static final FunctionDescriptor ffmnam$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffmnam$MH = RuntimeHelper.downcallHandle(
        "ffmnam",
        constants$149.ffmnam$FUNC
    );
    static final FunctionDescriptor ffmcom$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffmcom$MH = RuntimeHelper.downcallHandle(
        "ffmcom",
        constants$149.ffmcom$FUNC
    );
    static final FunctionDescriptor ffmkyu$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffmkyu$MH = RuntimeHelper.downcallHandle(
        "ffmkyu",
        constants$149.ffmkyu$FUNC
    );
    static final FunctionDescriptor ffmkys$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffmkys$MH = RuntimeHelper.downcallHandle(
        "ffmkys",
        constants$149.ffmkys$FUNC
    );
    static final FunctionDescriptor ffmkls$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffmkls$MH = RuntimeHelper.downcallHandle(
        "ffmkls",
        constants$149.ffmkls$FUNC
    );
}


