// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$5 {

    static final FunctionDescriptor memicmp$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle memicmp$MH = RuntimeHelper.downcallHandle(
        "memicmp",
        constants$5.memicmp$FUNC
    );
    static final FunctionDescriptor wcscat_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wcscat_s$MH = RuntimeHelper.downcallHandle(
        "wcscat_s",
        constants$5.wcscat_s$FUNC
    );
    static final FunctionDescriptor wcscpy_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wcscpy_s$MH = RuntimeHelper.downcallHandle(
        "wcscpy_s",
        constants$5.wcscpy_s$FUNC
    );
    static final FunctionDescriptor wcsncat_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle wcsncat_s$MH = RuntimeHelper.downcallHandle(
        "wcsncat_s",
        constants$5.wcsncat_s$FUNC
    );
    static final FunctionDescriptor wcsncpy_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle wcsncpy_s$MH = RuntimeHelper.downcallHandle(
        "wcsncpy_s",
        constants$5.wcsncpy_s$FUNC
    );
    static final FunctionDescriptor wcstok_s$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wcstok_s$MH = RuntimeHelper.downcallHandle(
        "wcstok_s",
        constants$5.wcstok_s$FUNC
    );
}


