// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$66 {

    static final FunctionDescriptor _vscanf_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vscanf_s_l$MH = RuntimeHelper.downcallHandle(
        "_vscanf_s_l",
        constants$66._vscanf_s_l$FUNC
    );
    static final FunctionDescriptor vscanf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vscanf_s$MH = RuntimeHelper.downcallHandle(
        "vscanf_s",
        constants$66.vscanf_s$FUNC
    );
    static final FunctionDescriptor _fscanf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _fscanf_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_fscanf_l",
        constants$66._fscanf_l$FUNC
    );
    static final FunctionDescriptor fscanf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fscanf$MH = RuntimeHelper.downcallHandleVariadic(
        "fscanf",
        constants$66.fscanf$FUNC
    );
    static final FunctionDescriptor _fscanf_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _fscanf_s_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_fscanf_s_l",
        constants$66._fscanf_s_l$FUNC
    );
    static final FunctionDescriptor fscanf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fscanf_s$MH = RuntimeHelper.downcallHandleVariadic(
        "fscanf_s",
        constants$66.fscanf_s$FUNC
    );
}


