// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$202 {

    static final FunctionDescriptor ffpgpujj$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffpgpujj$MH = RuntimeHelper.downcallHandle(
        "ffpgpujj",
        constants$202.ffpgpujj$FUNC
    );
    static final FunctionDescriptor fits_iter_set_by_name$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle fits_iter_set_by_name$MH = RuntimeHelper.downcallHandle(
        "fits_iter_set_by_name",
        constants$202.fits_iter_set_by_name$FUNC
    );
    static final FunctionDescriptor fits_iter_set_by_num$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle fits_iter_set_by_num$MH = RuntimeHelper.downcallHandle(
        "fits_iter_set_by_num",
        constants$202.fits_iter_set_by_num$FUNC
    );
    static final FunctionDescriptor fits_iter_set_file$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_iter_set_file$MH = RuntimeHelper.downcallHandle(
        "fits_iter_set_file",
        constants$202.fits_iter_set_file$FUNC
    );
    static final FunctionDescriptor fits_iter_set_colname$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_iter_set_colname$MH = RuntimeHelper.downcallHandle(
        "fits_iter_set_colname",
        constants$202.fits_iter_set_colname$FUNC
    );
    static final FunctionDescriptor fits_iter_set_colnum$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle fits_iter_set_colnum$MH = RuntimeHelper.downcallHandle(
        "fits_iter_set_colnum",
        constants$202.fits_iter_set_colnum$FUNC
    );
}


