// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$204 {

    static final FunctionDescriptor fits_iter_get_iotype$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_iter_get_iotype$MH = RuntimeHelper.downcallHandle(
        "fits_iter_get_iotype",
        constants$204.fits_iter_get_iotype$FUNC
    );
    static final FunctionDescriptor fits_iter_get_array$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_iter_get_array$MH = RuntimeHelper.downcallHandle(
        "fits_iter_get_array",
        constants$204.fits_iter_get_array$FUNC
    );
    static final FunctionDescriptor fits_iter_get_tlmin$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_iter_get_tlmin$MH = RuntimeHelper.downcallHandle(
        "fits_iter_get_tlmin",
        constants$204.fits_iter_get_tlmin$FUNC
    );
    static final FunctionDescriptor fits_iter_get_tlmax$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_iter_get_tlmax$MH = RuntimeHelper.downcallHandle(
        "fits_iter_get_tlmax",
        constants$204.fits_iter_get_tlmax$FUNC
    );
    static final FunctionDescriptor fits_iter_get_repeat$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_iter_get_repeat$MH = RuntimeHelper.downcallHandle(
        "fits_iter_get_repeat",
        constants$204.fits_iter_get_repeat$FUNC
    );
    static final FunctionDescriptor fits_iter_get_tunit$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_iter_get_tunit$MH = RuntimeHelper.downcallHandle(
        "fits_iter_get_tunit",
        constants$204.fits_iter_get_tunit$FUNC
    );
}


