// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$42 {

    static final FunctionDescriptor _vscwprintf_p$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vscwprintf_p$MH = RuntimeHelper.downcallHandle(
        "_vscwprintf_p",
        constants$42._vscwprintf_p$FUNC
    );
    static final FunctionDescriptor __swprintf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __swprintf_l$MH = RuntimeHelper.downcallHandleVariadic(
        "__swprintf_l",
        constants$42.__swprintf_l$FUNC
    );
    static final FunctionDescriptor _swprintf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _swprintf_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_swprintf_l",
        constants$42._swprintf_l$FUNC
    );
    static final FunctionDescriptor _swprintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _swprintf$MH = RuntimeHelper.downcallHandleVariadic(
        "_swprintf",
        constants$42._swprintf$FUNC
    );
    static final FunctionDescriptor swprintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle swprintf$MH = RuntimeHelper.downcallHandleVariadic(
        "swprintf",
        constants$42.swprintf$FUNC
    );
    static final FunctionDescriptor _swprintf_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _swprintf_s_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_swprintf_s_l",
        constants$42._swprintf_s_l$FUNC
    );
}


