// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$220 {

    static final FunctionDescriptor ffgtvf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffgtvf$MH = RuntimeHelper.downcallHandle(
        "ffgtvf",
        constants$220.ffgtvf$FUNC
    );
    static final FunctionDescriptor ffgtop$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffgtop$MH = RuntimeHelper.downcallHandle(
        "ffgtop",
        constants$220.ffgtop$FUNC
    );
    static final FunctionDescriptor ffgtam$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffgtam$MH = RuntimeHelper.downcallHandle(
        "ffgtam",
        constants$220.ffgtam$FUNC
    );
    static final FunctionDescriptor ffgtnm$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffgtnm$MH = RuntimeHelper.downcallHandle(
        "ffgtnm",
        constants$220.ffgtnm$FUNC
    );
    static final FunctionDescriptor ffgmng$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffgmng$MH = RuntimeHelper.downcallHandle(
        "ffgmng",
        constants$220.ffgmng$FUNC
    );
    static final FunctionDescriptor ffgmop$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffgmop$MH = RuntimeHelper.downcallHandle(
        "ffgmop",
        constants$220.ffgmop$FUNC
    );
}


