// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$15 {

    static final FunctionDescriptor wcsicoll$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wcsicoll$MH = RuntimeHelper.downcallHandle(
        "wcsicoll",
        constants$15.wcsicoll$FUNC
    );
    static final FunctionDescriptor strcpy_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle strcpy_s$MH = RuntimeHelper.downcallHandle(
        "strcpy_s",
        constants$15.strcpy_s$FUNC
    );
    static final FunctionDescriptor strcat_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle strcat_s$MH = RuntimeHelper.downcallHandle(
        "strcat_s",
        constants$15.strcat_s$FUNC
    );
    static final FunctionDescriptor strerror_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle strerror_s$MH = RuntimeHelper.downcallHandle(
        "strerror_s",
        constants$15.strerror_s$FUNC
    );
    static final FunctionDescriptor strncat_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle strncat_s$MH = RuntimeHelper.downcallHandle(
        "strncat_s",
        constants$15.strncat_s$FUNC
    );
    static final FunctionDescriptor strncpy_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle strncpy_s$MH = RuntimeHelper.downcallHandle(
        "strncpy_s",
        constants$15.strncpy_s$FUNC
    );
}


