// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$24 {

    static final FunctionDescriptor strdup$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle strdup$MH = RuntimeHelper.downcallHandle(
        "strdup",
        constants$24.strdup$FUNC
    );
    static final FunctionDescriptor strcmpi$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle strcmpi$MH = RuntimeHelper.downcallHandle(
        "strcmpi",
        constants$24.strcmpi$FUNC
    );
    static final FunctionDescriptor stricmp$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle stricmp$MH = RuntimeHelper.downcallHandle(
        "stricmp",
        constants$24.stricmp$FUNC
    );
    static final FunctionDescriptor strlwr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle strlwr$MH = RuntimeHelper.downcallHandle(
        "strlwr",
        constants$24.strlwr$FUNC
    );
    static final FunctionDescriptor strnicmp$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle strnicmp$MH = RuntimeHelper.downcallHandle(
        "strnicmp",
        constants$24.strnicmp$FUNC
    );
    static final FunctionDescriptor strnset$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle strnset$MH = RuntimeHelper.downcallHandle(
        "strnset",
        constants$24.strnset$FUNC
    );
}


