// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$226 {

    static final FunctionDescriptor fits_is_reentrant$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle fits_is_reentrant$MH = RuntimeHelper.downcallHandle(
        "fits_is_reentrant",
        constants$226.fits_is_reentrant$FUNC
    );
    static final FunctionDescriptor fits_decomp_img$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_decomp_img$MH = RuntimeHelper.downcallHandle(
        "fits_decomp_img",
        constants$226.fits_decomp_img$FUNC
    );
    static final FunctionDescriptor fits_img_decompress_header$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_img_decompress_header$MH = RuntimeHelper.downcallHandle(
        "fits_img_decompress_header",
        constants$226.fits_img_decompress_header$FUNC
    );
    static final FunctionDescriptor fits_img_decompress$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_img_decompress$MH = RuntimeHelper.downcallHandle(
        "fits_img_decompress",
        constants$226.fits_img_decompress$FUNC
    );
    static final FunctionDescriptor fits_hcompress$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_hcompress$MH = RuntimeHelper.downcallHandle(
        "fits_hcompress",
        constants$226.fits_hcompress$FUNC
    );
    static final FunctionDescriptor fits_hcompress64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_hcompress64$MH = RuntimeHelper.downcallHandle(
        "fits_hcompress64",
        constants$226.fits_hcompress64$FUNC
    );
}


