// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$6 {

    static final FunctionDescriptor _wcsdup$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcsdup$MH = RuntimeHelper.downcallHandle(
        "_wcsdup",
        constants$6._wcsdup$FUNC
    );
    static final FunctionDescriptor wcscat$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wcscat$MH = RuntimeHelper.downcallHandle(
        "wcscat",
        constants$6.wcscat$FUNC
    );
    static final FunctionDescriptor wcscmp$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wcscmp$MH = RuntimeHelper.downcallHandle(
        "wcscmp",
        constants$6.wcscmp$FUNC
    );
    static final FunctionDescriptor wcscpy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wcscpy$MH = RuntimeHelper.downcallHandle(
        "wcscpy",
        constants$6.wcscpy$FUNC
    );
    static final FunctionDescriptor wcscspn$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wcscspn$MH = RuntimeHelper.downcallHandle(
        "wcscspn",
        constants$6.wcscspn$FUNC
    );
    static final FunctionDescriptor wcslen$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wcslen$MH = RuntimeHelper.downcallHandle(
        "wcslen",
        constants$6.wcslen$FUNC
    );
}


