// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$228 {

    static final FunctionDescriptor ffvhtps$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ffvhtps$MH = RuntimeHelper.downcallHandle(
        "ffvhtps",
        constants$228.ffvhtps$FUNC
    );
    static final FunctionDescriptor ffshdwn$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ffshdwn$MH = RuntimeHelper.downcallHandle(
        "ffshdwn",
        constants$228.ffshdwn$FUNC
    );
    static final FunctionDescriptor ffgtmo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle ffgtmo$MH = RuntimeHelper.downcallHandle(
        "ffgtmo",
        constants$228.ffgtmo$FUNC
    );
    static final FunctionDescriptor ffstmo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffstmo$MH = RuntimeHelper.downcallHandle(
        "ffstmo",
        constants$228.ffstmo$FUNC
    );
    static final FunctionDescriptor fp_get_param$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fp_get_param$MH = RuntimeHelper.downcallHandle(
        "fp_get_param",
        constants$228.fp_get_param$FUNC
    );
    static final FunctionDescriptor abort_fpack$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle abort_fpack$MH = RuntimeHelper.downcallHandle(
        "abort_fpack",
        constants$228.abort_fpack$FUNC
    );
}


