// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$75 {

    static final FunctionDescriptor _sscanf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _sscanf_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_sscanf_l",
        constants$75._sscanf_l$FUNC
    );
    static final FunctionDescriptor sscanf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sscanf$MH = RuntimeHelper.downcallHandleVariadic(
        "sscanf",
        constants$75.sscanf$FUNC
    );
    static final FunctionDescriptor _sscanf_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _sscanf_s_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_sscanf_s_l",
        constants$75._sscanf_s_l$FUNC
    );
    static final FunctionDescriptor sscanf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sscanf_s$MH = RuntimeHelper.downcallHandleVariadic(
        "sscanf_s",
        constants$75.sscanf_s$FUNC
    );
    static final FunctionDescriptor _snscanf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _snscanf_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_snscanf_l",
        constants$75._snscanf_l$FUNC
    );
    static final FunctionDescriptor _snscanf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _snscanf$MH = RuntimeHelper.downcallHandleVariadic(
        "_snscanf",
        constants$75._snscanf$FUNC
    );
}


