// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$98 {

    static final FunctionDescriptor _get_fmode$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _get_fmode$MH = RuntimeHelper.downcallHandle(
        "_get_fmode",
        constants$98._get_fmode$FUNC
    );
    static final FunctionDescriptor abs$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle abs$MH = RuntimeHelper.downcallHandle(
        "abs",
        constants$98.abs$FUNC
    );
    static final FunctionDescriptor labs$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle labs$MH = RuntimeHelper.downcallHandle(
        "labs",
        constants$98.labs$FUNC
    );
    static final FunctionDescriptor llabs$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle llabs$MH = RuntimeHelper.downcallHandle(
        "llabs",
        constants$98.llabs$FUNC
    );
    static final FunctionDescriptor _abs64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _abs64$MH = RuntimeHelper.downcallHandle(
        "_abs64",
        constants$98._abs64$FUNC
    );
    static final FunctionDescriptor _byteswap_ushort$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle _byteswap_ushort$MH = RuntimeHelper.downcallHandle(
        "_byteswap_ushort",
        constants$98._byteswap_ushort$FUNC
    );
}


