// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$160 {

    static final FunctionDescriptor ffcdfl$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffcdfl$MH = RuntimeHelper.downcallHandle(
        "ffcdfl",
        constants$160.ffcdfl$FUNC
    );
    static final FunctionDescriptor ffwrhdu$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffwrhdu$MH = RuntimeHelper.downcallHandle(
        "ffwrhdu",
        constants$160.ffwrhdu$FUNC
    );
    static final FunctionDescriptor ffrdef$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffrdef$MH = RuntimeHelper.downcallHandle(
        "ffrdef",
        constants$160.ffrdef$FUNC
    );
    static final FunctionDescriptor ffrhdu$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffrhdu$MH = RuntimeHelper.downcallHandle(
        "ffrhdu",
        constants$160.ffrhdu$FUNC
    );
    static final FunctionDescriptor ffhdef$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffhdef$MH = RuntimeHelper.downcallHandle(
        "ffhdef",
        constants$160.ffhdef$FUNC
    );
    static final FunctionDescriptor ffpthp$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffpthp$MH = RuntimeHelper.downcallHandle(
        "ffpthp",
        constants$160.ffpthp$FUNC
    );
}


