// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$161 {

    static final FunctionDescriptor ffcsum$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffcsum$MH = RuntimeHelper.downcallHandle(
        "ffcsum",
        constants$161.ffcsum$FUNC
    );
    static final FunctionDescriptor ffesum$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffesum$MH = RuntimeHelper.downcallHandle(
        "ffesum",
        constants$161.ffesum$FUNC
    );
    static final FunctionDescriptor ffdsum$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffdsum$MH = RuntimeHelper.downcallHandle(
        "ffdsum",
        constants$161.ffdsum$FUNC
    );
    static final FunctionDescriptor ffpcks$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffpcks$MH = RuntimeHelper.downcallHandle(
        "ffpcks",
        constants$161.ffpcks$FUNC
    );
    static final FunctionDescriptor ffupck$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffupck$MH = RuntimeHelper.downcallHandle(
        "ffupck",
        constants$161.ffupck$FUNC
    );
    static final FunctionDescriptor ffvcks$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffvcks$MH = RuntimeHelper.downcallHandle(
        "ffvcks",
        constants$161.ffvcks$FUNC
    );
}


