// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$41 {

    static final FunctionDescriptor vswprintf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vswprintf_s$MH = RuntimeHelper.downcallHandle(
        "vswprintf_s",
        constants$41.vswprintf_s$FUNC
    );
    static final FunctionDescriptor _vswprintf_p_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vswprintf_p_l$MH = RuntimeHelper.downcallHandle(
        "_vswprintf_p_l",
        constants$41._vswprintf_p_l$FUNC
    );
    static final FunctionDescriptor _vswprintf_p$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vswprintf_p$MH = RuntimeHelper.downcallHandle(
        "_vswprintf_p",
        constants$41._vswprintf_p$FUNC
    );
    static final FunctionDescriptor _vscwprintf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vscwprintf_l$MH = RuntimeHelper.downcallHandle(
        "_vscwprintf_l",
        constants$41._vscwprintf_l$FUNC
    );
    static final FunctionDescriptor _vscwprintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vscwprintf$MH = RuntimeHelper.downcallHandle(
        "_vscwprintf",
        constants$41._vscwprintf$FUNC
    );
    static final FunctionDescriptor _vscwprintf_p_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vscwprintf_p_l$MH = RuntimeHelper.downcallHandle(
        "_vscwprintf_p_l",
        constants$41._vscwprintf_p_l$FUNC
    );
}


