// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$162 {

    static final FunctionDescriptor ffgcks$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffgcks$MH = RuntimeHelper.downcallHandle(
        "ffgcks",
        constants$162.ffgcks$FUNC
    );
    static final FunctionDescriptor ffpscl$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffpscl$MH = RuntimeHelper.downcallHandle(
        "ffpscl",
        constants$162.ffpscl$FUNC
    );
    static final FunctionDescriptor ffpnul$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffpnul$MH = RuntimeHelper.downcallHandle(
        "ffpnul",
        constants$162.ffpnul$FUNC
    );
    static final FunctionDescriptor fftscl$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fftscl$MH = RuntimeHelper.downcallHandle(
        "fftscl",
        constants$162.fftscl$FUNC
    );
    static final FunctionDescriptor fftnul$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fftnul$MH = RuntimeHelper.downcallHandle(
        "fftnul",
        constants$162.fftnul$FUNC
    );
    static final FunctionDescriptor ffsnul$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffsnul$MH = RuntimeHelper.downcallHandle(
        "ffsnul",
        constants$162.ffsnul$FUNC
    );
}


