// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$89 {

    static final FunctionDescriptor _wtoi64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wtoi64$MH = RuntimeHelper.downcallHandle(
        "_wtoi64",
        constants$89._wtoi64$FUNC
    );
    static final FunctionDescriptor _wtoi64_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wtoi64_l$MH = RuntimeHelper.downcallHandle(
        "_wtoi64_l",
        constants$89._wtoi64_l$FUNC
    );
    static final FunctionDescriptor _wcstoi64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _wcstoi64$MH = RuntimeHelper.downcallHandle(
        "_wcstoi64",
        constants$89._wcstoi64$FUNC
    );
    static final FunctionDescriptor _wcstoi64_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcstoi64_l$MH = RuntimeHelper.downcallHandle(
        "_wcstoi64_l",
        constants$89._wcstoi64_l$FUNC
    );
    static final FunctionDescriptor _wcstoui64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _wcstoui64$MH = RuntimeHelper.downcallHandle(
        "_wcstoui64",
        constants$89._wcstoui64$FUNC
    );
    static final FunctionDescriptor _wcstoui64_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcstoui64_l$MH = RuntimeHelper.downcallHandle(
        "_wcstoui64_l",
        constants$89._wcstoui64_l$FUNC
    );
}


