// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$38 {

    static final FunctionDescriptor _wscanf_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wscanf_s_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_wscanf_s_l",
        constants$38._wscanf_s_l$FUNC
    );
    static final FunctionDescriptor wscanf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wscanf_s$MH = RuntimeHelper.downcallHandleVariadic(
        "wscanf_s",
        constants$38.wscanf_s$FUNC
    );
    static final FunctionDescriptor __stdio_common_vswprintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __stdio_common_vswprintf$MH = RuntimeHelper.downcallHandle(
        "__stdio_common_vswprintf",
        constants$38.__stdio_common_vswprintf$FUNC
    );
    static final FunctionDescriptor __stdio_common_vswprintf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __stdio_common_vswprintf_s$MH = RuntimeHelper.downcallHandle(
        "__stdio_common_vswprintf_s",
        constants$38.__stdio_common_vswprintf_s$FUNC
    );
    static final FunctionDescriptor __stdio_common_vsnwprintf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __stdio_common_vsnwprintf_s$MH = RuntimeHelper.downcallHandle(
        "__stdio_common_vsnwprintf_s",
        constants$38.__stdio_common_vsnwprintf_s$FUNC
    );
    static final FunctionDescriptor __stdio_common_vswprintf_p$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __stdio_common_vswprintf_p$MH = RuntimeHelper.downcallHandle(
        "__stdio_common_vswprintf_p",
        constants$38.__stdio_common_vswprintf_p$FUNC
    );
}


