// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$118 {

    static final FunctionDescriptor CFITS2Unit$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CFITS2Unit$MH = RuntimeHelper.downcallHandle(
        "CFITS2Unit",
        constants$118.CFITS2Unit$FUNC
    );
    static final FunctionDescriptor CUnit2FITS$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CUnit2FITS$MH = RuntimeHelper.downcallHandle(
        "CUnit2FITS",
        constants$118.CUnit2FITS$FUNC
    );
    static final FunctionDescriptor fits_get_token$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_get_token$MH = RuntimeHelper.downcallHandle(
        "fits_get_token",
        constants$118.fits_get_token$FUNC
    );
    static final FunctionDescriptor fits_get_token2$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_get_token2$MH = RuntimeHelper.downcallHandle(
        "fits_get_token2",
        constants$118.fits_get_token2$FUNC
    );
    static final FunctionDescriptor fits_split_names$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_split_names$MH = RuntimeHelper.downcallHandle(
        "fits_split_names",
        constants$118.fits_split_names$FUNC
    );
    static final FunctionDescriptor ffiurl$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffiurl$MH = RuntimeHelper.downcallHandle(
        "ffiurl",
        constants$118.ffiurl$FUNC
    );
}


