// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$139 {

    static final FunctionDescriptor ffmaky$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffmaky$MH = RuntimeHelper.downcallHandle(
        "ffmaky",
        constants$139.ffmaky$FUNC
    );
    static final FunctionDescriptor ffmrky$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffmrky$MH = RuntimeHelper.downcallHandle(
        "ffmrky",
        constants$139.ffmrky$FUNC
    );
    static final FunctionDescriptor ffgnxk$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffgnxk$MH = RuntimeHelper.downcallHandle(
        "ffgnxk",
        constants$139.ffgnxk$FUNC
    );
    static final FunctionDescriptor ffgrec$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffgrec$MH = RuntimeHelper.downcallHandle(
        "ffgrec",
        constants$139.ffgrec$FUNC
    );
    static final FunctionDescriptor ffgcrd$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffgcrd$MH = RuntimeHelper.downcallHandle(
        "ffgcrd",
        constants$139.ffgcrd$FUNC
    );
    static final FunctionDescriptor ffgstr$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffgstr$MH = RuntimeHelper.downcallHandle(
        "ffgstr",
        constants$139.ffgstr$FUNC
    );
}


