// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$61 {

    static final FunctionDescriptor vfprintf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vfprintf_s$MH = RuntimeHelper.downcallHandle(
        "vfprintf_s",
        constants$61.vfprintf_s$FUNC
    );
    static final FunctionDescriptor _vfprintf_p_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vfprintf_p_l$MH = RuntimeHelper.downcallHandle(
        "_vfprintf_p_l",
        constants$61._vfprintf_p_l$FUNC
    );
    static final FunctionDescriptor _vfprintf_p$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vfprintf_p$MH = RuntimeHelper.downcallHandle(
        "_vfprintf_p",
        constants$61._vfprintf_p$FUNC
    );
    static final FunctionDescriptor _vprintf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vprintf_l$MH = RuntimeHelper.downcallHandle(
        "_vprintf_l",
        constants$61._vprintf_l$FUNC
    );
    static final FunctionDescriptor vprintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vprintf$MH = RuntimeHelper.downcallHandle(
        "vprintf",
        constants$61.vprintf$FUNC
    );
    static final FunctionDescriptor _vprintf_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vprintf_s_l$MH = RuntimeHelper.downcallHandle(
        "_vprintf_s_l",
        constants$61._vprintf_s_l$FUNC
    );
}


