// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$35 {

    static final FunctionDescriptor wprintf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wprintf_s$MH = RuntimeHelper.downcallHandleVariadic(
        "wprintf_s",
        constants$35.wprintf_s$FUNC
    );
    static final FunctionDescriptor _wprintf_p_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wprintf_p_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_wprintf_p_l",
        constants$35._wprintf_p_l$FUNC
    );
    static final FunctionDescriptor _wprintf_p$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wprintf_p$MH = RuntimeHelper.downcallHandleVariadic(
        "_wprintf_p",
        constants$35._wprintf_p$FUNC
    );
    static final FunctionDescriptor __stdio_common_vfwscanf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __stdio_common_vfwscanf$MH = RuntimeHelper.downcallHandle(
        "__stdio_common_vfwscanf",
        constants$35.__stdio_common_vfwscanf$FUNC
    );
    static final FunctionDescriptor _vfwscanf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vfwscanf_l$MH = RuntimeHelper.downcallHandle(
        "_vfwscanf_l",
        constants$35._vfwscanf_l$FUNC
    );
    static final FunctionDescriptor vfwscanf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vfwscanf$MH = RuntimeHelper.downcallHandle(
        "vfwscanf",
        constants$35.vfwscanf$FUNC
    );
}


