// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$28 {

    static final FunctionDescriptor ungetwc$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ungetwc$MH = RuntimeHelper.downcallHandle(
        "ungetwc",
        constants$28.ungetwc$FUNC
    );
    static final FunctionDescriptor _wfdopen$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wfdopen$MH = RuntimeHelper.downcallHandle(
        "_wfdopen",
        constants$28._wfdopen$FUNC
    );
    static final FunctionDescriptor _wfopen$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wfopen$MH = RuntimeHelper.downcallHandle(
        "_wfopen",
        constants$28._wfopen$FUNC
    );
    static final FunctionDescriptor _wfopen_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wfopen_s$MH = RuntimeHelper.downcallHandle(
        "_wfopen_s",
        constants$28._wfopen_s$FUNC
    );
    static final FunctionDescriptor _wfreopen$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wfreopen$MH = RuntimeHelper.downcallHandle(
        "_wfreopen",
        constants$28._wfreopen$FUNC
    );
    static final FunctionDescriptor _wfreopen_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wfreopen_s$MH = RuntimeHelper.downcallHandle(
        "_wfreopen_s",
        constants$28._wfreopen_s$FUNC
    );
}


