// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$222 {

    static final FunctionDescriptor fits_img_stats_float$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_img_stats_float$MH = RuntimeHelper.downcallHandle(
        "fits_img_stats_float",
        constants$222.fits_img_stats_float$FUNC
    );
    static final FunctionDescriptor fits_set_compression_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_set_compression_type$MH = RuntimeHelper.downcallHandle(
        "fits_set_compression_type",
        constants$222.fits_set_compression_type$FUNC
    );
    static final FunctionDescriptor fits_set_tile_dim$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_set_tile_dim$MH = RuntimeHelper.downcallHandle(
        "fits_set_tile_dim",
        constants$222.fits_set_tile_dim$FUNC
    );
    static final FunctionDescriptor fits_set_noise_bits$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_set_noise_bits$MH = RuntimeHelper.downcallHandle(
        "fits_set_noise_bits",
        constants$222.fits_set_noise_bits$FUNC
    );
    static final FunctionDescriptor fits_set_quantize_level$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_set_quantize_level$MH = RuntimeHelper.downcallHandle(
        "fits_set_quantize_level",
        constants$222.fits_set_quantize_level$FUNC
    );
    static final FunctionDescriptor fits_set_hcomp_scale$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_set_hcomp_scale$MH = RuntimeHelper.downcallHandle(
        "fits_set_hcomp_scale",
        constants$222.fits_set_hcomp_scale$FUNC
    );
}


