// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$46 {

    static final FunctionDescriptor _vsnwscanf_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vsnwscanf_s_l$MH = RuntimeHelper.downcallHandle(
        "_vsnwscanf_s_l",
        constants$46._vsnwscanf_s_l$FUNC
    );
    static final FunctionDescriptor _swscanf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _swscanf_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_swscanf_l",
        constants$46._swscanf_l$FUNC
    );
    static final FunctionDescriptor swscanf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle swscanf$MH = RuntimeHelper.downcallHandleVariadic(
        "swscanf",
        constants$46.swscanf$FUNC
    );
    static final FunctionDescriptor _swscanf_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _swscanf_s_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_swscanf_s_l",
        constants$46._swscanf_s_l$FUNC
    );
    static final FunctionDescriptor swscanf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle swscanf_s$MH = RuntimeHelper.downcallHandleVariadic(
        "swscanf_s",
        constants$46.swscanf_s$FUNC
    );
    static final FunctionDescriptor _snwscanf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _snwscanf_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_snwscanf_l",
        constants$46._snwscanf_l$FUNC
    );
}


