// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$126 {

    static final FunctionDescriptor ffgerr$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffgerr$MH = RuntimeHelper.downcallHandle(
        "ffgerr",
        constants$126.ffgerr$FUNC
    );
    static final FunctionDescriptor ffpmsg$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffpmsg$MH = RuntimeHelper.downcallHandle(
        "ffpmsg",
        constants$126.ffpmsg$FUNC
    );
    static final FunctionDescriptor ffpmrk$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle ffpmrk$MH = RuntimeHelper.downcallHandle(
        "ffpmrk",
        constants$126.ffpmrk$FUNC
    );
    static final FunctionDescriptor ffgmsg$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffgmsg$MH = RuntimeHelper.downcallHandle(
        "ffgmsg",
        constants$126.ffgmsg$FUNC
    );
    static final FunctionDescriptor ffcmsg$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle ffcmsg$MH = RuntimeHelper.downcallHandle(
        "ffcmsg",
        constants$126.ffcmsg$FUNC
    );
    static final FunctionDescriptor ffcmrk$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle ffcmrk$MH = RuntimeHelper.downcallHandle(
        "ffcmrk",
        constants$126.ffcmrk$FUNC
    );
}


