// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$32 {

    static final FunctionDescriptor vfwprintf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vfwprintf_s$MH = RuntimeHelper.downcallHandle(
        "vfwprintf_s",
        constants$32.vfwprintf_s$FUNC
    );
    static final FunctionDescriptor _vfwprintf_p_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vfwprintf_p_l$MH = RuntimeHelper.downcallHandle(
        "_vfwprintf_p_l",
        constants$32._vfwprintf_p_l$FUNC
    );
    static final FunctionDescriptor _vfwprintf_p$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vfwprintf_p$MH = RuntimeHelper.downcallHandle(
        "_vfwprintf_p",
        constants$32._vfwprintf_p$FUNC
    );
    static final FunctionDescriptor _vwprintf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vwprintf_l$MH = RuntimeHelper.downcallHandle(
        "_vwprintf_l",
        constants$32._vwprintf_l$FUNC
    );
    static final FunctionDescriptor vwprintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle vwprintf$MH = RuntimeHelper.downcallHandle(
        "vwprintf",
        constants$32.vwprintf$FUNC
    );
    static final FunctionDescriptor _vwprintf_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _vwprintf_s_l$MH = RuntimeHelper.downcallHandle(
        "_vwprintf_s_l",
        constants$32._vwprintf_s_l$FUNC
    );
}


