// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$233 {

    static final FunctionDescriptor fp_i4rescale$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fp_i4rescale$MH = RuntimeHelper.downcallHandle(
        "fp_i4rescale",
        constants$233.fp_i4rescale$FUNC
    );
    static final FunctionDescriptor fp_msg$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fp_msg$MH = RuntimeHelper.downcallHandle(
        "fp_msg",
        constants$233.fp_msg$FUNC
    );
    static final FunctionDescriptor fp_version$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle fp_version$MH = RuntimeHelper.downcallHandle(
        "fp_version",
        constants$233.fp_version$FUNC
    );
    static final FunctionDescriptor fp_noop$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle fp_noop$MH = RuntimeHelper.downcallHandle(
        "fp_noop",
        constants$233.fp_noop$FUNC
    );
    static final FunctionDescriptor fu_get_param$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fu_get_param$MH = RuntimeHelper.downcallHandle(
        "fu_get_param",
        constants$233.fu_get_param$FUNC
    );
    static final FunctionDescriptor fu_usage$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle fu_usage$MH = RuntimeHelper.downcallHandle(
        "fu_usage",
        constants$233.fu_usage$FUNC
    );
}


