// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1 {

    static final FunctionDescriptor _invalid_parameter_noinfo_noreturn$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle _invalid_parameter_noinfo_noreturn$MH = RuntimeHelper.downcallHandle(
        "_invalid_parameter_noinfo_noreturn",
        constants$1._invalid_parameter_noinfo_noreturn$FUNC
    );
    static final FunctionDescriptor _invoke_watson$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _invoke_watson$MH = RuntimeHelper.downcallHandle(
        "_invoke_watson",
        constants$1._invoke_watson$FUNC
    );
    static final FunctionDescriptor _errno$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle _errno$MH = RuntimeHelper.downcallHandle(
        "_errno",
        constants$1._errno$FUNC
    );
    static final FunctionDescriptor _set_errno$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _set_errno$MH = RuntimeHelper.downcallHandle(
        "_set_errno",
        constants$1._set_errno$FUNC
    );
    static final FunctionDescriptor _get_errno$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _get_errno$MH = RuntimeHelper.downcallHandle(
        "_get_errno",
        constants$1._get_errno$FUNC
    );
    static final FunctionDescriptor __doserrno$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle __doserrno$MH = RuntimeHelper.downcallHandle(
        "__doserrno",
        constants$1.__doserrno$FUNC
    );
}


