// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$37 {

    static final FunctionDescriptor _fwscanf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _fwscanf_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_fwscanf_l",
        constants$37._fwscanf_l$FUNC
    );
    static final FunctionDescriptor fwscanf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fwscanf$MH = RuntimeHelper.downcallHandleVariadic(
        "fwscanf",
        constants$37.fwscanf$FUNC
    );
    static final FunctionDescriptor _fwscanf_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _fwscanf_s_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_fwscanf_s_l",
        constants$37._fwscanf_s_l$FUNC
    );
    static final FunctionDescriptor fwscanf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fwscanf_s$MH = RuntimeHelper.downcallHandleVariadic(
        "fwscanf_s",
        constants$37.fwscanf_s$FUNC
    );
    static final FunctionDescriptor _wscanf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wscanf_l$MH = RuntimeHelper.downcallHandleVariadic(
        "_wscanf_l",
        constants$37._wscanf_l$FUNC
    );
    static final FunctionDescriptor wscanf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wscanf$MH = RuntimeHelper.downcallHandleVariadic(
        "wscanf",
        constants$37.wscanf$FUNC
    );
}


