// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$103 {

    static final FunctionDescriptor _atodbl$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _atodbl$MH = RuntimeHelper.downcallHandle(
        "_atodbl",
        constants$103._atodbl$FUNC
    );
    static final FunctionDescriptor _atoldbl$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _atoldbl$MH = RuntimeHelper.downcallHandle(
        "_atoldbl",
        constants$103._atoldbl$FUNC
    );
    static final FunctionDescriptor _atoflt_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _atoflt_l$MH = RuntimeHelper.downcallHandle(
        "_atoflt_l",
        constants$103._atoflt_l$FUNC
    );
    static final FunctionDescriptor _atodbl_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _atodbl_l$MH = RuntimeHelper.downcallHandle(
        "_atodbl_l",
        constants$103._atodbl_l$FUNC
    );
    static final FunctionDescriptor _atoldbl_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _atoldbl_l$MH = RuntimeHelper.downcallHandle(
        "_atoldbl_l",
        constants$103._atoldbl_l$FUNC
    );
    static final FunctionDescriptor strtof$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle strtof$MH = RuntimeHelper.downcallHandle(
        "strtof",
        constants$103.strtof$FUNC
    );
}


