// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$30 {

    static final FunctionDescriptor _wtmpnam$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wtmpnam$MH = RuntimeHelper.downcallHandle(
        "_wtmpnam",
        constants$30._wtmpnam$FUNC
    );
    static final FunctionDescriptor _fgetwc_nolock$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _fgetwc_nolock$MH = RuntimeHelper.downcallHandle(
        "_fgetwc_nolock",
        constants$30._fgetwc_nolock$FUNC
    );
    static final FunctionDescriptor _fputwc_nolock$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _fputwc_nolock$MH = RuntimeHelper.downcallHandle(
        "_fputwc_nolock",
        constants$30._fputwc_nolock$FUNC
    );
    static final FunctionDescriptor _getwc_nolock$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _getwc_nolock$MH = RuntimeHelper.downcallHandle(
        "_getwc_nolock",
        constants$30._getwc_nolock$FUNC
    );
    static final FunctionDescriptor _putwc_nolock$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _putwc_nolock$MH = RuntimeHelper.downcallHandle(
        "_putwc_nolock",
        constants$30._putwc_nolock$FUNC
    );
    static final FunctionDescriptor _ungetwc_nolock$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _ungetwc_nolock$MH = RuntimeHelper.downcallHandle(
        "_ungetwc_nolock",
        constants$30._ungetwc_nolock$FUNC
    );
}


