// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$128 {

    static final FunctionDescriptor ffnkey$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffnkey$MH = RuntimeHelper.downcallHandle(
        "ffnkey",
        constants$128.ffnkey$FUNC
    );
    static final FunctionDescriptor ffgkcl$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffgkcl$MH = RuntimeHelper.downcallHandle(
        "ffgkcl",
        constants$128.ffgkcl$FUNC
    );
    static final FunctionDescriptor ffdtyp$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffdtyp$MH = RuntimeHelper.downcallHandle(
        "ffdtyp",
        constants$128.ffdtyp$FUNC
    );
    static final FunctionDescriptor ffinttyp$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffinttyp$MH = RuntimeHelper.downcallHandle(
        "ffinttyp",
        constants$128.ffinttyp$FUNC
    );
    static final FunctionDescriptor ffpsvc$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffpsvc$MH = RuntimeHelper.downcallHandle(
        "ffpsvc",
        constants$128.ffpsvc$FUNC
    );
    static final FunctionDescriptor ffgknm$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffgknm$MH = RuntimeHelper.downcallHandle(
        "ffgknm",
        constants$128.ffgknm$FUNC
    );
}


