// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$224 {

    static final FunctionDescriptor fits_set_huge_hdu$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_set_huge_hdu$MH = RuntimeHelper.downcallHandle(
        "fits_set_huge_hdu",
        constants$224.fits_set_huge_hdu$FUNC
    );
    static final FunctionDescriptor fits_set_compression_pref$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_set_compression_pref$MH = RuntimeHelper.downcallHandle(
        "fits_set_compression_pref",
        constants$224.fits_set_compression_pref$FUNC
    );
    static final FunctionDescriptor fits_get_compression_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_get_compression_type$MH = RuntimeHelper.downcallHandle(
        "fits_get_compression_type",
        constants$224.fits_get_compression_type$FUNC
    );
    static final FunctionDescriptor fits_get_tile_dim$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_get_tile_dim$MH = RuntimeHelper.downcallHandle(
        "fits_get_tile_dim",
        constants$224.fits_get_tile_dim$FUNC
    );
    static final FunctionDescriptor fits_get_quantize_level$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_get_quantize_level$MH = RuntimeHelper.downcallHandle(
        "fits_get_quantize_level",
        constants$224.fits_get_quantize_level$FUNC
    );
    static final FunctionDescriptor fits_get_noise_bits$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fits_get_noise_bits$MH = RuntimeHelper.downcallHandle(
        "fits_get_noise_bits",
        constants$224.fits_get_noise_bits$FUNC
    );
}


