// Generated by jextract

package gov.nasa.gsfc.heasarc.cfitsio;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$127 {

    static final FunctionDescriptor ffrprt$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ffrprt$MH = RuntimeHelper.downcallHandle(
        "ffrprt",
        constants$127.ffrprt$FUNC
    );
    static final FunctionDescriptor ffcmps$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffcmps$MH = RuntimeHelper.downcallHandle(
        "ffcmps",
        constants$127.ffcmps$FUNC
    );
    static final FunctionDescriptor fftkey$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fftkey$MH = RuntimeHelper.downcallHandle(
        "fftkey",
        constants$127.fftkey$FUNC
    );
    static final FunctionDescriptor fftrec$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fftrec$MH = RuntimeHelper.downcallHandle(
        "fftrec",
        constants$127.fftrec$FUNC
    );
    static final FunctionDescriptor ffnchk$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffnchk$MH = RuntimeHelper.downcallHandle(
        "ffnchk",
        constants$127.ffnchk$FUNC
    );
    static final FunctionDescriptor ffkeyn$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ffkeyn$MH = RuntimeHelper.downcallHandle(
        "ffkeyn",
        constants$127.ffkeyn$FUNC
    );
}


